# packages in environment at /Users/ad_loris/miniconda3/envs/py:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyhd3eb1b0_0  
appnope                   0.1.2           py311hca03da5_1001  
argcomplete               1.12.3             pyhd3eb1b0_0  
argh                      0.26.2          py311hca03da5_0  
asttokens                 2.0.5              pyhd3eb1b0_0    anaconda
attrs                     23.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
bcbio-gff                 0.6.9                    pypi_0    pypi
biopython                 1.78            py311h80987f9_0  
blas                      1.0                    openblas  
bottleneck                1.3.5           py311ha0d4635_0  
brotli                    1.0.9                h1a8c8d9_9    conda-forge
brotli-bin                1.0.9                h1a8c8d9_9    conda-forge
brotlipy                  0.7.0           py311h80987f9_1002  
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.0               h80987f9_0  
ca-certificates           2024.7.4             hf0a4a13_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h80987f9_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
comm                      0.1.2           py311hca03da5_0  
contourpy                 1.0.5           py311h48ca7d4_0  
cryptography              39.0.1          py311h834c97f_2  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1           py311h313beb8_0  
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
demes                     0.2.3              pyhd8ed1ab_0    conda-forge
dendropy                  4.6.1                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0    anaconda
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.12.1               h1192e45_0  
gettext                   0.21.0               h826f4ad_0    anaconda
gffutils                  0.12               pyh7cba7a3_0    bioconda
giflib                    5.2.1                h80987f9_3  
glib                      2.69.1               h98b2900_1    anaconda
gsl                       2.7                  h6e638da_0    conda-forge
gst-plugins-base          1.14.1               hf0a386a_0    anaconda
gstreamer                 1.14.1               he09cfb7_0    anaconda
h5py                      3.7.0           py311h39e7838_0  
hdf5                      1.12.1               h05c076b_3  
icu                       68.1                 hc377ac9_0    anaconda
idna                      3.4             py311hca03da5_0  
importlib-metadata        4.11.3          py311hca03da5_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
importlib_resources       6.0.0              pyhd8ed1ab_1    conda-forge
ipykernel                 6.19.2          py311h37496c9_0  
ipython                   8.12.0          py311hca03da5_0  
jedi                      0.18.1          py311hca03da5_1  
joblib                    1.2.0           py311hca03da5_0    anaconda
jpeg                      9e                   h80987f9_1  
jsonschema                4.18.3             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.6.1           pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.12             pyhd3eb1b0_0    anaconda
jupyter_core              5.3.0           py311hca03da5_0  
kiwisolver                1.4.4           py311h313beb8_0  
krb5                      1.20.1               hf3e1bf2_1  
lcms2                     2.12                 hba8e193_0  
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           17_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_9    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_9    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_9    conda-forge
libcblas                  3.9.0           17_osxarm64_openblas    conda-forge
libclang                  12.0.0          default_hc321e17_4    anaconda
libcurl                   8.1.1                h3e2b118_1  
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20221030         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libiconv                  1.16                 h1a28f6b_2    anaconda
liblapack                 3.9.0           17_osxarm64_openblas    conda-forge
libllvm12                 12.0.0               h12f7ac0_4    anaconda
libllvm14                 14.0.6               hd1a9a77_4    conda-forge
libnghttp2                1.52.0               h62f6fdd_1  
libopenblas               0.3.23          openmp_hc731615_0    conda-forge
libpng                    1.6.39               h80987f9_0  
libpq                     12.15                h02f6b3c_1  
libsodium                 1.0.18               h1a28f6b_0    anaconda
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.10.0               h02f6b3c_2  
libtiff                   4.2.0                had003b8_2  
libwebp                   1.2.4                ha3663a8_1  
libwebp-base              1.2.4                h80987f9_1  
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.9.14               h8c5e841_0    anaconda
libxslt                   1.1.35               h9833966_0    anaconda
libzlib                   1.2.13               h53f4e23_5    conda-forge
llvm-openmp               18.1.8               hde57baf_0    conda-forge
llvmlite                  0.42.0          py311hf5d242d_1    conda-forge
lz4-c                     1.9.4                h313beb8_0  
matplotlib-base           3.7.1           py311h7aedaa7_1  
matplotlib-inline         0.1.2              pyhd3eb1b0_2    anaconda
msprime                   1.2.0           py311h850a081_2    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
nest-asyncio              1.5.1              pyhd3eb1b0_0    anaconda
networkx                  2.7.1              pyhd3eb1b0_0    anaconda
nspr                      4.33                 hc377ac9_0    anaconda
nss                       3.74                 h142855e_0    anaconda
numba                     0.59.1          py311h00351ea_0    conda-forge
numexpr                   2.8.4           py311h6dc990b_1  
numpy                     1.24.3          py311hb57d4eb_0    anaconda
numpy-base                1.24.3          py311h1d85a46_0    anaconda
openssl                   3.3.1                hfb2fe0b_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py311h6956b77_0  
parso                     0.8.3              pyhd3eb1b0_0    anaconda
patsy                     0.5.3           py311hca03da5_0  
pcre                      8.45                 hc377ac9_0    anaconda
pexpect                   4.8.0              pyhd3eb1b0_3    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    9.4.0           py311h313beb8_0  
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.2           py311hca03da5_0  
ply                       3.11            py311hca03da5_0  
pooch                     1.4.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.36          py311hca03da5_0  
psutil                    5.9.0           py311h80987f9_0  
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2    anaconda
pure_eval                 0.2.2              pyhd3eb1b0_0    anaconda
pycparser                 2.21               pyhd3eb1b0_0  
pyfaidx                   0.7.2.1            pyh7cba7a3_1    bioconda
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pyopenssl                 23.0.0          py311hca03da5_0  
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py311h313beb8_0  
pyqt5-sip                 12.11.0         py311h313beb8_0  
pysocks                   1.7.1           py311hca03da5_0  
python                    3.11.4          h47c9636_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    anaconda
pyvcf3                    1.0.3              pyhdfd78af_0    bioconda
pyyaml                    6.0             py311h80987f9_1  
pyzmq                     25.1.0          py311h313beb8_0  
qt-main                   5.15.2               ha2d02b5_7  
qt-webengine              5.15.9               h2903aaf_7  
qtwebkit                  5.212                h0f11f3c_4  
readline                  8.2                  h92ec313_1    conda-forge
referencing               0.29.1             pyhd8ed1ab_0    conda-forge
requests                  2.29.0          py311hca03da5_0  
rpds-py                   0.8.10          py311h0563b04_0    conda-forge
ruamel.yaml               0.17.32         py311heffc1b2_0    conda-forge
ruamel.yaml.clib          0.2.7           py311he2be06e_1    conda-forge
scikit-learn              1.3.0           py311h7aedaa7_0    anaconda
scipy                     1.10.1          py311hc76d9b0_1  
seaborn                   0.12.2               hd8ed1ab_0    conda-forge
seaborn-base              0.12.2             pyhd8ed1ab_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
simplejson                3.17.6          py311h80987f9_0  
sip                       6.6.2           py311h313beb8_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.41.2               h80987f9_0  
stack_data                0.2.0              pyhd3eb1b0_0    anaconda
statsmodels               0.13.5          py311h80987f9_1  
svgwrite                  1.4.3              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh0d69192_0    anaconda
tk                        8.6.12               hb8d0fd4_0  
toml                      0.10.2             pyhd3eb1b0_0    anaconda
tornado                   6.2             py311h80987f9_0  
traitlets                 5.7.1           py311hca03da5_0  
treetime                  0.9.2              pyh5e36f6f_0    bioconda
tskit                     0.5.5           py311hb49d859_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
upsetplot                 0.8.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.16         py311hca03da5_0  
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.4.2                h80987f9_0  
yaml                      0.2.5                h1a28f6b_0    anaconda
zeromq                    4.3.4                hc377ac9_0    anaconda
zipp                      3.16.0             pyhd8ed1ab_1    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zstd                      1.5.5                hd90d995_0  
