# packages in environment at /u/iclight/bin/miniconda3/envs/basic_genomics:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
bamutil                   1.0.15               h2e03b76_1    bioconda
bcbio-gff                 0.7.0              pyh7cba7a3_0    bioconda
bcftools                  1.2                  h02bfda8_4    bioconda
bedtools                  2.30.0               h7d7f7ad_2    bioconda
binutils_impl_linux-64    2.35.1               h27ae35d_9  
binutils_linux-64         2.35.1              h454624a_30  
biopython                 1.79             py39h3811e60_1    conda-forge
bwa                       0.7.17               h5bf99c6_8    bioconda
bwidget                   1.9.14               ha770c72_0    conda-forge
bx-python                 0.8.11           py39h5d76eff_1    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.2               h7f98852_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
curl                      7.78.0               hea6ffbf_0    conda-forge
enabrowsertools           1.5.4                         0    bioconda
entrez-direct             16.2                 he881be0_0    bioconda
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gatk                      3.8                 hdfd78af_11    bioconda
gcc_impl_linux-64         9.3.0               h6df7d76_17  
gcc_linux-64              9.3.0               h1ee779e_30  
genbank_to                0.42               pyhdfd78af_0    bioconda
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
gfortran_impl_linux-64    9.3.0               h5abd6ed_17  
gfortran_linux-64         9.3.0               hf47db2c_30  
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
gxx_impl_linux-64         9.3.0               hbdd7822_17  
gxx_linux-64              9.3.0               h7e70986_30  
harfbuzz                  2.8.2                h83ec7ef_0    conda-forge
htslib                    1.13                 h9093b5e_0    bioconda
icu                       68.1                 h58526e2_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
jq                        1.5                           0    bioconda
kernel-headers_linux-64   2.6.32              he073ed8_14    conda-forge
krb5                      1.19.2               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               h7274673_9  
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libcurl                   7.78.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-devel_linux-64     9.3.0               hb95220a_17  
libgcc-ng                 11.1.0               hc902ee8_8    conda-forge
libgfortran-ng            9.3.0               ha5ec8a7_17  
libgfortran5              9.3.0               ha5ec8a7_17  
libglib                   2.68.3               h3e27bee_0    conda-forge
libgomp                   11.1.0               hc902ee8_8    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-devel_linux-64  9.3.0               hf0c5c8d_17  
libstdcxx-ng              11.1.0               h56837e0_8    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
mapdamage2                2.2.1                   pyr40_0    bioconda
ncbi-datasets-cli         12.23.0              h4bd325d_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.22.3           py39hc58783e_2    conda-forge
openblas                  0.3.17          pthreads_h4748800_1    conda-forge
openjdk                   8.0.282              h7f98852_0    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
pandas                    1.4.2            py39h1832856_1    conda-forge
pango                     1.48.7               hb8ff022_0    conda-forge
parallel                  20211022             ha770c72_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
perl                      5.32.1          0_h7f98852_perl5    conda-forge
picard                    2.27.5               hdfd78af_0    bioconda
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
preseq                    2.0.3                hc216eb9_5    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pysam                     0.16.0.1         py39h051187c_3    bioconda
python                    3.9.6           h49503c6_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-lzo                1.14             py39h388aed1_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
qualimap                  2.2.2a                        1    bioconda
r-assertthat              0.2.1             r40hc72bb7e_2    conda-forge
r-backports               1.2.1             r40hcfec24a_0    conda-forge
r-base                    4.0.5                hb67fd72_2    conda-forge
r-bitops                  1.0_7             r40hcfec24a_0    conda-forge
r-brio                    1.1.2             r40hcfec24a_0    conda-forge
r-callr                   3.7.0             r40hc72bb7e_0    conda-forge
r-catools                 1.18.2            r40h03ef668_0    conda-forge
r-cli                     3.0.1             r40h03ef668_1    conda-forge
r-codetools               0.2_18            r40hc72bb7e_0    conda-forge
r-colorspace              2.0_2             r40hcfec24a_0    conda-forge
r-crayon                  1.4.1             r40hc72bb7e_0    conda-forge
r-desc                    1.3.0             r40hc72bb7e_0    conda-forge
r-diffobj                 0.3.4             r40hcfec24a_0    conda-forge
r-digest                  0.6.27            r40h03ef668_0    conda-forge
r-ellipsis                0.3.2             r40hcfec24a_0    conda-forge
r-evaluate                0.14              r40hc72bb7e_2    conda-forge
r-fansi                   0.5.0             r40hcfec24a_0    conda-forge
r-farver                  2.1.0             r40h03ef668_0    conda-forge
r-foreach                 1.5.2             r40hc72bb7e_0    conda-forge
r-gam                     1.20              r40h859d828_1    conda-forge
r-getopt                  1.20.3            r40ha770c72_2    conda-forge
r-ggplot2                 3.3.5             r40hc72bb7e_0    conda-forge
r-glue                    1.4.2             r40hcfec24a_0    conda-forge
r-gplots                  3.1.1             r40hc72bb7e_0    conda-forge
r-gridbase                0.4_7           r40hc72bb7e_1003    conda-forge
r-gridextra               2.3             r40hc72bb7e_1003    conda-forge
r-gsalib                  2.1             r40ha770c72_1002    conda-forge
r-gtable                  0.3.0             r40hc72bb7e_3    conda-forge
r-gtools                  3.9.2             r40hcfec24a_0    conda-forge
r-inline                  0.3.19            r40hc72bb7e_0    conda-forge
r-isoband                 0.2.5             r40h03ef668_0    conda-forge
r-iterators               1.0.14            r40hc72bb7e_0    conda-forge
r-jsonlite                1.7.2             r40hcfec24a_0    conda-forge
r-kernsmooth              2.23_20           r40h742201e_0    conda-forge
r-labeling                0.4.2             r40hc72bb7e_0    conda-forge
r-lattice                 0.20_44           r40hcfec24a_0    conda-forge
r-lifecycle               1.0.0             r40hc72bb7e_0    conda-forge
r-magrittr                2.0.1             r40hcfec24a_1    conda-forge
r-mass                    7.3_54            r40hcfec24a_0    conda-forge
r-matrix                  1.3_4             r40he454529_0    conda-forge
r-mgcv                    1.8_36            r40he454529_0    conda-forge
r-munsell                 0.5.0           r40hc72bb7e_1003    conda-forge
r-nlme                    3.1_152           r40h859d828_0    conda-forge
r-pillar                  1.6.2             r40hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r40hc72bb7e_1    conda-forge
r-pkgload                 1.2.1             r40h03ef668_0    conda-forge
r-plyr                    1.8.6             r40h03ef668_1    conda-forge
r-praise                  1.0.0           r40hc72bb7e_1004    conda-forge
r-processx                3.5.2             r40hcfec24a_0    conda-forge
r-ps                      1.6.0             r40hcfec24a_0    conda-forge
r-r6                      2.5.0             r40hc72bb7e_0    conda-forge
r-rcolorbrewer            1.1_2           r40h785f33e_1003    conda-forge
r-rcpp                    1.0.7             r40h03ef668_0    conda-forge
r-rcppgsl                 0.3.11            r40hcec875b_0    conda-forge
r-rematch2                2.1.2             r40hc72bb7e_1    conda-forge
r-reshape                 0.8.8             r40hcfec24a_2    conda-forge
r-rlang                   0.4.11            r40hcfec24a_0    conda-forge
r-rprojroot               2.0.2             r40hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r40hc72bb7e_0    conda-forge
r-scales                  1.1.1             r40hc72bb7e_0    conda-forge
r-testthat                3.0.4             r40h03ef668_0    conda-forge
r-tibble                  3.1.3             r40hcfec24a_0    conda-forge
r-utf8                    1.2.2             r40hcfec24a_0    conda-forge
r-vctrs                   0.3.8             r40hcfec24a_1    conda-forge
r-viridislite             0.4.0             r40hc72bb7e_0    conda-forge
r-waldo                   0.2.5             r40hc72bb7e_0    conda-forge
r-withr                   2.4.2             r40hc72bb7e_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
samtools                  1.13                 h8c37831_0    bioconda
sed                       4.8                  he412f7d_0    conda-forge
seqtk                     1.3                  h5bf99c6_3    bioconda
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
sra-tools                 2.8.0                         0    bioconda
sysroot_linux-64          2.12                he073ed8_14    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
wgsim                     1.0                  h5bf99c6_4    bioconda
wheel                     0.37.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
